"""Control Gate - Intent-native AI automation control platform."""

from control_gate.contracts import (
    FINANCE_V1_POLICY,
    REQUEST_ADMISSIBILITY_LABELS,
    RUNTIME_BENCHMARK_BUCKETS,
    ApprovalRule,
    ControlDecision,
    Decision,
    EventType,
    ExecutionPlan,
    ExecutionRun,
    Goal,
    HumanAction,
    HumanIntervention,
    IntentActor,
    IntentSpec,
    Permissions,
    PlanStep,
    PolicySet,
    RetryRule,
    RunOutcome,
    RunState,
    TrajectoryEvent,
)

__version__ = "0.1.0"

__all__ = [
    "FINANCE_V1_POLICY",
    "REQUEST_ADMISSIBILITY_LABELS",
    "RUNTIME_BENCHMARK_BUCKETS",
    "ApprovalRule",
    "ControlDecision",
    "Decision",
    "EventType",
    "ExecutionPlan",
    "ExecutionRun",
    "Goal",
    "HumanAction",
    "HumanIntervention",
    "IntentActor",
    "IntentSpec",
    "Permissions",
    "PlanStep",
    "PolicySet",
    "RetryRule",
    "RunOutcome",
    "RunState",
    "TrajectoryEvent",
    "__version__",
]
